#!/bin/csh -f
#
#
if ( $# < 3 ) then
 echo "Usage: $0 <DM> <Freq2> <Freq1>"
 echo "  DM   - in pc/cm^3"
 echo "  Freq1, Freq2 - in MHz"
 echo "The program gives a value of dispersion delay in ms"
 exit 0
else
 echo "scale=30" > .dide
 echo "((10000000*$1)/(2.41))*((1/($2*$2))-(1/($3*$3)))" >> .dide
 echo "Delay = `bc -l < .dide` ms"
 rm .dide
endif

